#!/usr/bin/env bash

OS_TYPE=`uname`
CURRENT_PATH=$(pwd)

function init_vim_file()
{
    rm -rf ~/.vim
    rm -f ~/.vimrc
    rm -f ~/.vimrc.keybind
    rm -f ~/.vimrc.local
    rm -f ~/.vimrc.plugin
    rm -f ~/.vimrc.plugin.local
    rm -f ~/.tmux.conf

    ln -s "${CURRENT_PATH}/vim" ~/.vim
    ln -s "${CURRENT_PATH}/_vimrc" ~/.vimrc
    ln -s "${CURRENT_PATH}/_vimrc.keybind" ~/.vimrc.keybind
    ln -s "${CURRENT_PATH}/_vimrc.local" ~/.vimrc.local
    ln -s "${CURRENT_PATH}/_vimrc.plugin" ~/.vimrc.plugin
    ln -s "${CURRENT_PATH}/_vimrc.plugin.local" ~/.vimrc.plugin.local
    ln -s "${CURRENT_PATH}/tmux.conf" ~/.tmux.conf
}

function init_linux_font()
{
    mkdir -p ~/.fonts
    unzip "${CURRENT_PATH}/fonts/consolas-powerline-vim-master.zip" -d ~/.fonts
    cp -f ~/.fonts/consolas-powerline-vim-master/*.ttf ~/.fonts
    rm -rf ~/.fonts/consolas-powerline-vim-master
    cd ~/.fonts
    mkfontscale
    mkfontdir
}

if [ "${OS_TYPE}" = "Darwin" ]; then
    init_vim_file;
elif [ "${OS_TYPE}" = "Linux" ]; then
    init_vim_file;
    init_linux_font;
else
    echo "Unsupported OS type"
    exit 1
fi
