#!/usr/bin/env python
# -*- coding: utf-8 -*-

import json
import os
import re
from flask import Flask
from flask import request
from flask import Response

import sys
reload(sys)
sys.setdefaultencoding('utf-8')

#MD_DIR = '/Users/mdl/vimwiki/'
MD_DIR = '<path_to_your_vimwiki_dir>'

app = Flask(__name__)
app.debug = True


def grep(filename, regex_obj):
    path = os.path.join(MD_DIR, filename)
    if regex_obj.search(filename):
        return True
    with open(path, 'r') as f:
        file_content = f.readlines()
        file_content = [x.strip() for x in file_content]
        file_content = ''.join(file_content)
        return regex_obj.search(file_content) is not None


def get_match_filelist(regex_text):
    res = []
    regex_obj = re.compile(regex_text, re.I | re.M | re.S | re.L | re.X)
    for filename in os.listdir(MD_DIR):
        if filename.endswith('.md'):
            try:
                if grep(filename, regex_obj):
                    res.append(filename[:-2] + 'html')
            except Exception, _ex:
                print str(_ex)
    return res


def ajax_return(res, msg='', data=u'', **kwargs):
    result = {}
    result.update(kwargs)
    result["success"] = res
    result["msg"] = msg
    result["data"] = data
    return json.dumps(result)


@app.route("/vimwiki/search", methods=['GET', 'POST'])
def search():
    regex_text = request.args.get('q', '').encode('utf8')
    print regex_text
    jsonpCallback = request.args.get('jsonpCallback')
    res = get_match_filelist(regex_text)
    for i in res:
        print i
    res = jsonpCallback + "(" + json.dumps(res) + ")"
    print res
    return Response(res, status=200, mimetype='application/json')


if __name__ == "__main__":
    app.run()
